name: Publish Jar
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release git tag
        type: string
        required: true
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: mythiccontrol
          settings-path: ${{ github.workspace }}
      - name: Build Mods with Maven
        run: mvn package
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-jar
          path: ./target/*.jar
      - name: Publish release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./target/*.jar
          tag: ${{ inputs.tag }}
          name: MythicControl ${{ inputs.tag }}
          allowUpdates: true
          artifactErrorsFailBuild: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}